package lozadagroupcompany;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrameRVList extends javax.swing.JFrame {

    DatabaseConnection conn = new DatabaseConnection();
    DefaultTableModel tablemodel;
    Connection connection = conn.getConnection();
    DefaultTableModel dm;
    int particulars;

    public FrameRVList() {
        initComponents();
        RetrieveData();
    }

    private void RetrieveData() {
        DefaultTableModel TableModel = (DefaultTableModel) tablerv.getModel();
        while (TableModel.getRowCount() > 0) {
            TableModel.removeRow(0);
        }
        try (Statement stmt = connection.createStatement()) {
            ResultSet rs = stmt.executeQuery("SELECT * FROM tblreceiptvoucher");
            while (rs.next()) {
                String code = rs.getString("ReceiptCode");
                String acc = rs.getString("Account");
                String payor = rs.getString("Payor");
                String tin = rs.getString("TINNumber");
                String deposited = rs.getString("DepositedTo");
                String description = rs.getString("Description");
                String pparticulars = rs.getString("Particulars");
                String gross = rs.getString("GrossAmount");
                String vat = rs.getString("VAT");
                String netvat = rs.getString("NetVAT");
                String prepared = rs.getString("PreparedBy");
                String verified = rs.getString("VerifiedBy");
                String approved = rs.getString("ApprovedBy");
                String received = rs.getString("ReceivedBy");
                String status = rs.getString("Status");
                String date = rs.getString("Date");
                TableModel.addRow(new Object[]{code, acc, payor, tin, deposited, description, pparticulars, gross, vat, netvat, prepared, verified, approved, received, status, date});
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblcode = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableparticular = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablerv = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jButton2.setBackground(new java.awt.Color(45, 52, 66));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(45, 52, 66));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RECEIPT VOUCHER LIST");

        lblcode.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblcode.setForeground(new java.awt.Color(255, 153, 0));
        lblcode.setText("000000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcode)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblcode))
                .addContainerGap())
        );

        jButton3.setBackground(new java.awt.Color(45, 52, 66));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Import");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tableparticular.setBackground(new java.awt.Color(107, 115, 131));
        tableparticular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableparticular.setForeground(new java.awt.Color(255, 255, 255));
        tableparticular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Particular", "Quantity", "Unit", "Unit Cost", "GrossAmount", "VAT Type", "VAT", "NetVAT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableparticular.setGridColor(new java.awt.Color(204, 204, 204));
        tableparticular.setSelectionBackground(new java.awt.Color(45, 52, 66));
        tableparticular.setSelectionForeground(new java.awt.Color(235, 235, 236));
        tableparticular.setShowHorizontalLines(true);
        tableparticular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableparticularMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tableparticular);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Search...");

        tablerv.setBackground(new java.awt.Color(107, 115, 131));
        tablerv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablerv.setForeground(new java.awt.Color(255, 255, 255));
        tablerv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RV Code", "Account", "Payor", "TIN", "Deposited To", "Description", "Particulars", "Gross Amount", "VAT", "NetVAT", "Prepared By", "Verified By", "Approved By", "Received By", "Status", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablerv.setGridColor(new java.awt.Color(204, 204, 204));
        tablerv.setSelectionBackground(new java.awt.Color(45, 52, 66));
        tablerv.setSelectionForeground(new java.awt.Color(235, 235, 236));
        tablerv.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablerv.setShowHorizontalLines(true);
        tablerv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablervMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tablerv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FrameReceiptVoucher frame = new FrameReceiptVoucher();
        frame.setVisible(true);
        int row = tablerv.getSelectedRow();
        if (row > -1) {
            String code = tablerv.getValueAt(row, 0).toString();
            String acc = tablerv.getValueAt(row, 1).toString();
            String payor = tablerv.getValueAt(row, 2).toString();
            String tin = tablerv.getValueAt(row, 3).toString();
            String deposit = tablerv.getValueAt(row, 4).toString();
            String des = tablerv.getValueAt(row, 5).toString();
            String part = tablerv.getValueAt(row, 6).toString();
            String gross = tablerv.getValueAt(row, 7).toString();
            String vat = tablerv.getValueAt(row, 8).toString();
            String netvat = tablerv.getValueAt(row, 9).toString();
            String receive = tablerv.getValueAt(row, 11).toString();
            FrameReceiptVoucher.LoadRV(code, acc, payor, tin, deposit, des, part, gross, vat, netvat, receive);
            for (int i = 0; i < tableparticular.getRowCount(); i++) {
                String pcode = tableparticular.getValueAt(i, 0).toString();
                String ppart = tableparticular.getValueAt(i, 1).toString();
                String pquantity = tableparticular.getValueAt(i, 2).toString();
                String punit = tableparticular.getValueAt(i, 3).toString();
                String pcost = tableparticular.getValueAt(i, 4).toString();
                String pgross = tableparticular.getValueAt(i, 5).toString();
                String vattype = tableparticular.getValueAt(i, 6).toString();
                String pvat = tableparticular.getValueAt(i, 7).toString();
                String pnetvat = tableparticular.getValueAt(i, 8).toString();
                FrameReceiptVoucher.LoadRVParticular(new Object[]{
                    pcode,
                    ppart,
                    pquantity,
                    punit,
                    pcost,
                    pgross,
                    vattype,
                    pvat,
                    pnetvat,});
            }
            JOptionPane.showMessageDialog(this, "Receipt Voucher '" + lblcode.getText() + "' is added to the list.", " System Information", JOptionPane.INFORMATION_MESSAGE);

            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Please select an item.", " System Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableparticularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableparticularMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableparticularMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrameDisbursementVoucher frame = new FrameDisbursementVoucher();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablervMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablervMouseClicked
        int row = tablerv.getSelectedRow();
        if (row > -1) {
            DefaultTableModel TableModel1 = (DefaultTableModel) tablerv.getModel();
            DefaultTableModel TableModel2 = (DefaultTableModel) tableparticular.getModel();
            lblcode.setText(TableModel1.getValueAt(row, 0).toString());
            while (TableModel2.getRowCount() > 0) {
                TableModel2.removeRow(0);
            }
            try (Statement stmt = connection.createStatement()) {
                ResultSet rs = stmt.executeQuery("SELECT * FROM tblreceiptvoucherparticular WHERE ReceiptCode = '" + lblcode.getText() + "' ");
                while (rs.next()) {
                    String rvcode = rs.getString("ReceiptCode");
                    String code = rs.getString("Code");
                    String particular = rs.getString("Particular");
                    String quantity = rs.getString("Quantity");
                    String unit = rs.getString("Unit");
                    String unitcost = rs.getString("UnitCost");
                    String gross = rs.getString("PGrossAmount");
                    String vat = rs.getString("PVAT");
                    String netvat = rs.getString("PNetVAT");
                    TableModel2.addRow(new Object[]{rvcode, code, particular, quantity, unit, unitcost, gross, vat, netvat});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Can't read record in system table!\nSystem detects changes in table entities!\nPlease contact the backend developer.", "ERROR 1012", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tablervMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRVList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRVList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRVList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRVList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameRVList().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblcode;
    private javax.swing.JTable tableparticular;
    private javax.swing.JTable tablerv;
    // End of variables declaration//GEN-END:variables
}
